name: 'Check env/userscript/bin/collect-anime-data'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/userscript/bin/collect-anime-data/**'
      - '.github/workflows/_check-userscript-bin-collect-anime-data.yml'
      - '!env/userscript/bin/collect-anime-data/dist/**'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/userscript/bin/collect-anime-data/**'
      - '.github/workflows/_check-userscript-bin-collect-anime-data.yml'
      - '!env/userscript/bin/collect-anime-data/dist/**'

  schedule:
    - cron: '0 * * * *'

  workflow_dispatch:

jobs:
  update:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          token: '${{ secrets.BOT_GITHUB_TOKEN }}'

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'env/userscript/bin/collect-anime-data/go.mod'
          cache: true
          cache-dependency-path: 'env/userscript/bin/collect-anime-data/go.sum'

      - name: Generate
        run: BASE_DIR=. go run ./
        working-directory: 'env/userscript/bin/collect-anime-data'

      - name: Pull
        run: git pull

      - name: Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '⚙️ Build (env/userscript/bin/collect-anime-data)'
          commit_author: 'StarryBlueSky-bot <97773209+StarryBlueSky-bot@users.noreply.github.com>'
