name: 'Check env/github'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/github/**'
      - '.github/workflows/_check-github.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/github/**'
      - '.github/workflows/_check-github.yml'

  workflow_dispatch:

  #  schedule:
  #    - cron: '0 0 * * *'

jobs:
  build:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-run.yml
    with:
      script: 'workspace @slashnephy/github-config build'
    permissions:
      contents: 'read'

  lint:
    if: github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-lint.yml
    with:
      script: 'workspace @slashnephy/github-config lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request' && github.event_name != 'schedule'
    uses: ./.github/workflows/yarn-format.yml
    with:
      script: 'workspace @slashnephy/github-config format'
    permissions:
      contents: 'write'

  # Reusable workflow に secrets を渡すには事前に渡すキーをワークフロー側で定義しておく必要があり面倒
  #  update:
  #    if: github.event_name != 'pull_request'
  #    uses: ./.github/workflows/yarn-run.yml
  #    with:
  #      working-directory: 'env/github'
  #      script: 'start'
  #      env: |
  #        GITHUB_TOKEN=${{ secrets.GH_PAT }}
  #        USER_WEBHOOK_URL=${{ secrets.USER_WEBHOOK_URL }}
  #        ORG_WEBHOOK_URL=${{ secrets.ORG_WEBHOOK_URL }}
  #    secrets: inherit
  #    permissions:
  #      contents: 'read'
