name: 'Check env/prettier'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/prettier/**'
      - '.github/workflows/_check-prettier.yml'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/prettier/**'
      - '.github/workflows/_check-prettier.yml'

  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      pre-script: 'workspace @slashnephy/prettier-config build'
      script: 'workspace @slashnephy/prettier-config lint'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      pre-script: 'workspace @slashnephy/prettier-config build'
      script: 'workspace @slashnephy/prettier-config format'
    permissions:
      contents: 'write'

  publish:
    if: github.event_name == 'push'
    needs: lint
    uses: ./.github/workflows/yarn-publish.yml
    with:
      working-directory: 'env/prettier'
      pre-script: 'workspace @slashnephy/prettier-config bump-version'
      script: 'workspace @slashnephy/prettier-config publish'
      commit-message: 'ðŸ”¨ Bump version'
    permissions:
      contents: 'write'
    secrets:
      NODE_AUTH_TOKEN: '${{ secrets.NPM_ACCESS_TOKEN }}'
