name: 'Check env/userscript'

on:
  push:
    branches:
      - 'master'
    paths:
      - 'env/userscript/**'
      - '.github/workflows/_check-userscript.yml'
      - '!env/userscript/bin/*/dist/*'

  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - 'env/userscript/**'
      - '.github/workflows/_check-userscript.yml'
      - '!env/userscript/bin/*/dist/*'

  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/yarn-run.yml
    with:
      working-directory: 'env/userscript'
      script: 'build'
    permissions:
      contents: 'read'

  lint:
    uses: ./.github/workflows/yarn-lint.yml
    with:
      working-directory: 'env/userscript'
    permissions:
      contents: 'read'
      pull-requests: 'write'

  format-and-build-ci:
    if: github.event_name != 'pull_request'
    uses: ./.github/workflows/yarn-format.yml
    with:
      working-directory: 'env/userscript'
      script: ''
      command: 'NODE_OPTIONS="--max-old-space-size=8172" yarn ci'
      commit-message: '⚙️ Build (env/userscript)'
    permissions:
      contents: 'write'
